export const toLeetCode = {
  'Array': 'array',
  'String': 'string',
  'Hash Table': 'hash-table',
  'Math': 'math',
  'Dynamic Programming': 'dynamic-programming',
  'Sorting': 'sorting',
  'Greedy': 'greedy',
  'Binary Search': 'binary-search',
  'Depth-First Search': 'depth-first-search',
  'Bit Manipulation': 'bit-manipulation',
  'Matrix': 'matrix',
  'Tree': 'tree',
  'Breadth-First Search': 'breadth-first-search',
  'Two Pointers': 'two-pointers',
  'Prefix Sum': 'prefix-sum',
  'Heap (Priority Queue)': 'heap-priority-queue',
  'Simulation': 'simulation',
  'Counting': 'counting',
  'Graph Theory': 'graph',
  'Binary Tree': 'binary-tree',
  'Stack': 'stack',
  'Sliding Window': 'sliding-window',
  'Enumeration': 'enumeration',
  'Design': 'design',
  'Backtracking': 'backtracking',
  'Union-Find': 'union-find',
  'Number Theory': 'number-theory',
  'Linked List': 'linked-list',
  'Segment Tree': 'segment-tree',
  'Ordered Set': 'ordered-set',
  'Monotonic Stack': 'monotonic-stack',
  'Divide and Conquer': 'divide-and-conquer',
  'Combinatorics': 'combinatorics',
  'Trie': 'trie',
  'Bitmask': 'bitmask',
  'Queue': 'queue',
  'Recursion': 'recursion',
  'Geometry': 'geometry',
  'Binary Indexed Tree': 'binary-indexed-tree',
  'Hash Function': 'hash-function',
  'Memoization': 'memoization',
  'Binary Search Tree': 'binary-search-tree',
  'Topological Sort': 'topological-sort',
  'Shortest Path': 'shortest-path',
  'String Matching': 'string-matching',
  'Rolling Hash': 'rolling-hash',
  'Game Theory': 'game-theory',
  'Sweep Line': 'line-sweep',
  'Minimum Spanning Tree': 'minimum-spanning-tree',
};

export const topicMap = toLeetCode; // Backward compatibility fallback

export default toLeetCode;
