export const PROBLEM_TOPICS = [
  'Array',
  'String',
  'Hash Table',
  'Math',
  'Dynamic Programming',
  'Sorting',
  'Greedy',
  'Binary Search',
  'Depth-First Search',
  'Bit Manipulation',
  'Matrix',
  'Tree',
  'Breadth-First Search',
  'Two Pointers',
  'Prefix Sum',
  'Heap (Priority Queue)',
  'Simulation',
  'Counting',
  'Graph Theory',
  'Binary Tree',
  'Stack',
  'Sliding Window',
  'Enumeration',
  'Design',
  'Backtracking',
  'Union-Find',
  'Number Theory',
  'Linked List',
  'Segment Tree',
  'Ordered Set',
  'Monotonic Stack',
  'Divide and Conquer',
  'Combinatorics',
  'Trie',
  'Bitmask',
  'Queue',
  'Recursion',
  'Geometry',
  'Binary Indexed Tree',
  'Hash Function',
  'Memoization',
  'Binary Search Tree',
  'Topological Sort',
  'Shortest Path',
  'String Matching',
  'Rolling Hash',
  'Game Theory',
  'Sweep Line',
  'Minimum Spanning Tree'
];
