export const PROBLEM_TOPICS = [
  'Array',
  'String',
  'Hash Table',
  'Math',
  'Dynamic Programming',
  'Sorting',
  'Greedy',
  'Binary Search',
  'Bit Manipulation',
  'Matrix',
  'Two Pointers',
  'Counting',
  'Stack',
  'Sliding Window',
  'Backtracking',
  'Linked List',
  'Divide and Conquer',
  'Recursion',
  'Memoization'
];
